package com.ll.pojo;

public class Appointment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.id
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.student_name
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.trainer_name
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String trainerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointment_time
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String appointmentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.student_idCard
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String studentIdcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointment_ap
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String appointmentAp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.test_subject
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String testSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.student_phone
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String studentPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointment_clicktime
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String appointmentClicktime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.id
     *
     * @return the value of appointment.id
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.id
     *
     * @param id the value for appointment.id
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.student_name
     *
     * @return the value of appointment.student_name
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.student_name
     *
     * @param studentName the value for appointment.student_name
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.trainer_name
     *
     * @return the value of appointment.trainer_name
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getTrainerName() {
        return trainerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.trainer_name
     *
     * @param trainerName the value for appointment.trainer_name
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setTrainerName(String trainerName) {
        this.trainerName = trainerName == null ? null : trainerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointment_time
     *
     * @return the value of appointment.appointment_time
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getAppointmentTime() {
        return appointmentTime+"  "+appointmentAp+"点";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointment_time
     *
     * @param appointmentTime the value for appointment.appointment_time
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setAppointmentTime(String appointmentTime) {
        this.appointmentTime = appointmentTime == null ? null : appointmentTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.student_idCard
     *
     * @return the value of appointment.student_idCard
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getStudentIdcard() {
        return studentIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.student_idCard
     *
     * @param studentIdcard the value for appointment.student_idCard
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setStudentIdcard(String studentIdcard) {
        this.studentIdcard = studentIdcard == null ? null : studentIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointment_ap
     *
     * @return the value of appointment.appointment_ap
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getAppointmentAp() {
        return appointmentAp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointment_ap
     *
     * @param appointmentAp the value for appointment.appointment_ap
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setAppointmentAp(String appointmentAp) {
        this.appointmentAp = appointmentAp == null ? null : appointmentAp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.test_subject
     *
     * @return the value of appointment.test_subject
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getTestSubject() {
        return testSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.test_subject
     *
     * @param testSubject the value for appointment.test_subject
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setTestSubject(String testSubject) {
        this.testSubject = testSubject == null ? null : testSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.student_phone
     *
     * @return the value of appointment.student_phone
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getStudentPhone() {
        return studentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.student_phone
     *
     * @param studentPhone the value for appointment.student_phone
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setStudentPhone(String studentPhone) {
        this.studentPhone = studentPhone == null ? null : studentPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointment_clicktime
     *
     * @return the value of appointment.appointment_clicktime
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getAppointmentClicktime() {
        return appointmentClicktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointment_clicktime
     *
     * @param appointmentClicktime the value for appointment.appointment_clicktime
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setAppointmentClicktime(String appointmentClicktime) {
        this.appointmentClicktime = appointmentClicktime == null ? null : appointmentClicktime.trim();
    }
}