package com.ll.pojo;

public class Publishmessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish_message.id
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish_message.message_date
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String messageDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish_message.message_info
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String messageInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish_message.id
     *
     * @return the value of publish_message.id
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish_message.id
     *
     * @param id the value for publish_message.id
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish_message.message_date
     *
     * @return the value of publish_message.message_date
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getMessageDate() {
        return messageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish_message.message_date
     *
     * @param messageDate the value for publish_message.message_date
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setMessageDate(String messageDate) {
        this.messageDate = messageDate == null ? null : messageDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish_message.message_info
     *
     * @return the value of publish_message.message_info
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getMessageInfo() {
        return messageInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish_message.message_info
     *
     * @param messageInfo the value for publish_message.message_info
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setMessageInfo(String messageInfo) {
        this.messageInfo = messageInfo == null ? null : messageInfo.trim();
    }
}