package com.ll.pojo;

public class ReadyTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ready_test.id
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ready_test.student_name
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ready_test.student_idCard
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String studentIdcard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ready_test.id
     *
     * @return the value of ready_test.id
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ready_test.id
     *
     * @param id the value for ready_test.id
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ready_test.student_name
     *
     * @return the value of ready_test.student_name
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ready_test.student_name
     *
     * @param studentName the value for ready_test.student_name
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ready_test.student_idCard
     *
     * @return the value of ready_test.student_idCard
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getStudentIdcard() {
        return studentIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ready_test.student_idCard
     *
     * @param studentIdcard the value for ready_test.student_idCard
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setStudentIdcard(String studentIdcard) {
        this.studentIdcard = studentIdcard == null ? null : studentIdcard.trim();
    }
}