package com.ll.pojo;

import java.util.ArrayList;
import java.util.List;

public class StudentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public StudentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNull() {
            addCriterion("student_name is null");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNotNull() {
            addCriterion("student_name is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNameEqualTo(String value) {
            addCriterion("student_name =", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotEqualTo(String value) {
            addCriterion("student_name <>", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThan(String value) {
            addCriterion("student_name >", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThanOrEqualTo(String value) {
            addCriterion("student_name >=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThan(String value) {
            addCriterion("student_name <", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThanOrEqualTo(String value) {
            addCriterion("student_name <=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLike(String value) {
            addCriterion("student_name like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotLike(String value) {
            addCriterion("student_name not like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameIn(List<String> values) {
            addCriterion("student_name in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotIn(List<String> values) {
            addCriterion("student_name not in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameBetween(String value1, String value2) {
            addCriterion("student_name between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotBetween(String value1, String value2) {
            addCriterion("student_name not between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardIsNull() {
            addCriterion("student_idCard is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardIsNotNull() {
            addCriterion("student_idCard is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardEqualTo(String value) {
            addCriterion("student_idCard =", value, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardNotEqualTo(String value) {
            addCriterion("student_idCard <>", value, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardGreaterThan(String value) {
            addCriterion("student_idCard >", value, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardGreaterThanOrEqualTo(String value) {
            addCriterion("student_idCard >=", value, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardLessThan(String value) {
            addCriterion("student_idCard <", value, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardLessThanOrEqualTo(String value) {
            addCriterion("student_idCard <=", value, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardLike(String value) {
            addCriterion("student_idCard like", value, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardNotLike(String value) {
            addCriterion("student_idCard not like", value, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardIn(List<String> values) {
            addCriterion("student_idCard in", values, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardNotIn(List<String> values) {
            addCriterion("student_idCard not in", values, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardBetween(String value1, String value2) {
            addCriterion("student_idCard between", value1, value2, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentIdcardNotBetween(String value1, String value2) {
            addCriterion("student_idCard not between", value1, value2, "studentIdcard");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIsNull() {
            addCriterion("student_phone is null");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIsNotNull() {
            addCriterion("student_phone is not null");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneEqualTo(String value) {
            addCriterion("student_phone =", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotEqualTo(String value) {
            addCriterion("student_phone <>", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneGreaterThan(String value) {
            addCriterion("student_phone >", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("student_phone >=", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLessThan(String value) {
            addCriterion("student_phone <", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLessThanOrEqualTo(String value) {
            addCriterion("student_phone <=", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLike(String value) {
            addCriterion("student_phone like", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotLike(String value) {
            addCriterion("student_phone not like", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIn(List<String> values) {
            addCriterion("student_phone in", values, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotIn(List<String> values) {
            addCriterion("student_phone not in", values, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneBetween(String value1, String value2) {
            addCriterion("student_phone between", value1, value2, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotBetween(String value1, String value2) {
            addCriterion("student_phone not between", value1, value2, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentProjectIsNull() {
            addCriterion("student_project is null");
            return (Criteria) this;
        }

        public Criteria andStudentProjectIsNotNull() {
            addCriterion("student_project is not null");
            return (Criteria) this;
        }

        public Criteria andStudentProjectEqualTo(String value) {
            addCriterion("student_project =", value, "studentProject");
            return (Criteria) this;
        }

        public Criteria andStudentProjectNotEqualTo(String value) {
            addCriterion("student_project <>", value, "studentProject");
            return (Criteria) this;
        }

        public Criteria andStudentProjectGreaterThan(String value) {
            addCriterion("student_project >", value, "studentProject");
            return (Criteria) this;
        }

        public Criteria andStudentProjectGreaterThanOrEqualTo(String value) {
            addCriterion("student_project >=", value, "studentProject");
            return (Criteria) this;
        }

        public Criteria andStudentProjectLessThan(String value) {
            addCriterion("student_project <", value, "studentProject");
            return (Criteria) this;
        }

        public Criteria andStudentProjectLessThanOrEqualTo(String value) {
            addCriterion("student_project <=", value, "studentProject");
            return (Criteria) this;
        }

        public Criteria andStudentProjectLike(String value) {
            addCriterion("student_project like", value, "studentProject");
            return (Criteria) this;
        }

        public Criteria andStudentProjectNotLike(String value) {
            addCriterion("student_project not like", value, "studentProject");
            return (Criteria) this;
        }

        public Criteria andStudentProjectIn(List<String> values) {
            addCriterion("student_project in", values, "studentProject");
            return (Criteria) this;
        }

        public Criteria andStudentProjectNotIn(List<String> values) {
            addCriterion("student_project not in", values, "studentProject");
            return (Criteria) this;
        }

        public Criteria andStudentProjectBetween(String value1, String value2) {
            addCriterion("student_project between", value1, value2, "studentProject");
            return (Criteria) this;
        }

        public Criteria andStudentProjectNotBetween(String value1, String value2) {
            addCriterion("student_project not between", value1, value2, "studentProject");
            return (Criteria) this;
        }

        public Criteria andStudentCartimeIsNull() {
            addCriterion("student_cartime is null");
            return (Criteria) this;
        }

        public Criteria andStudentCartimeIsNotNull() {
            addCriterion("student_cartime is not null");
            return (Criteria) this;
        }

        public Criteria andStudentCartimeEqualTo(String value) {
            addCriterion("student_cartime =", value, "studentCartime");
            return (Criteria) this;
        }

        public Criteria andStudentCartimeNotEqualTo(String value) {
            addCriterion("student_cartime <>", value, "studentCartime");
            return (Criteria) this;
        }

        public Criteria andStudentCartimeGreaterThan(String value) {
            addCriterion("student_cartime >", value, "studentCartime");
            return (Criteria) this;
        }

        public Criteria andStudentCartimeGreaterThanOrEqualTo(String value) {
            addCriterion("student_cartime >=", value, "studentCartime");
            return (Criteria) this;
        }

        public Criteria andStudentCartimeLessThan(String value) {
            addCriterion("student_cartime <", value, "studentCartime");
            return (Criteria) this;
        }

        public Criteria andStudentCartimeLessThanOrEqualTo(String value) {
            addCriterion("student_cartime <=", value, "studentCartime");
            return (Criteria) this;
        }

        public Criteria andStudentCartimeLike(String value) {
            addCriterion("student_cartime like", value, "studentCartime");
            return (Criteria) this;
        }

        public Criteria andStudentCartimeNotLike(String value) {
            addCriterion("student_cartime not like", value, "studentCartime");
            return (Criteria) this;
        }

        public Criteria andStudentCartimeIn(List<String> values) {
            addCriterion("student_cartime in", values, "studentCartime");
            return (Criteria) this;
        }

        public Criteria andStudentCartimeNotIn(List<String> values) {
            addCriterion("student_cartime not in", values, "studentCartime");
            return (Criteria) this;
        }

        public Criteria andStudentCartimeBetween(String value1, String value2) {
            addCriterion("student_cartime between", value1, value2, "studentCartime");
            return (Criteria) this;
        }

        public Criteria andStudentCartimeNotBetween(String value1, String value2) {
            addCriterion("student_cartime not between", value1, value2, "studentCartime");
            return (Criteria) this;
        }

        public Criteria andStudentTimeIsNull() {
            addCriterion("student_time is null");
            return (Criteria) this;
        }

        public Criteria andStudentTimeIsNotNull() {
            addCriterion("student_time is not null");
            return (Criteria) this;
        }

        public Criteria andStudentTimeEqualTo(Integer value) {
            addCriterion("student_time =", value, "studentTime");
            return (Criteria) this;
        }

        public Criteria andStudentTimeNotEqualTo(Integer value) {
            addCriterion("student_time <>", value, "studentTime");
            return (Criteria) this;
        }

        public Criteria andStudentTimeGreaterThan(Integer value) {
            addCriterion("student_time >", value, "studentTime");
            return (Criteria) this;
        }

        public Criteria andStudentTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_time >=", value, "studentTime");
            return (Criteria) this;
        }

        public Criteria andStudentTimeLessThan(Integer value) {
            addCriterion("student_time <", value, "studentTime");
            return (Criteria) this;
        }

        public Criteria andStudentTimeLessThanOrEqualTo(Integer value) {
            addCriterion("student_time <=", value, "studentTime");
            return (Criteria) this;
        }

        public Criteria andStudentTimeIn(List<Integer> values) {
            addCriterion("student_time in", values, "studentTime");
            return (Criteria) this;
        }

        public Criteria andStudentTimeNotIn(List<Integer> values) {
            addCriterion("student_time not in", values, "studentTime");
            return (Criteria) this;
        }

        public Criteria andStudentTimeBetween(Integer value1, Integer value2) {
            addCriterion("student_time between", value1, value2, "studentTime");
            return (Criteria) this;
        }

        public Criteria andStudentTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("student_time not between", value1, value2, "studentTime");
            return (Criteria) this;
        }

        public Criteria andStudentSatusIsNull() {
            addCriterion("student_satus is null");
            return (Criteria) this;
        }

        public Criteria andStudentSatusIsNotNull() {
            addCriterion("student_satus is not null");
            return (Criteria) this;
        }

        public Criteria andStudentSatusEqualTo(Integer value) {
            addCriterion("student_satus =", value, "studentSatus");
            return (Criteria) this;
        }

        public Criteria andStudentSatusNotEqualTo(Integer value) {
            addCriterion("student_satus <>", value, "studentSatus");
            return (Criteria) this;
        }

        public Criteria andStudentSatusGreaterThan(Integer value) {
            addCriterion("student_satus >", value, "studentSatus");
            return (Criteria) this;
        }

        public Criteria andStudentSatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_satus >=", value, "studentSatus");
            return (Criteria) this;
        }

        public Criteria andStudentSatusLessThan(Integer value) {
            addCriterion("student_satus <", value, "studentSatus");
            return (Criteria) this;
        }

        public Criteria andStudentSatusLessThanOrEqualTo(Integer value) {
            addCriterion("student_satus <=", value, "studentSatus");
            return (Criteria) this;
        }

        public Criteria andStudentSatusIn(List<Integer> values) {
            addCriterion("student_satus in", values, "studentSatus");
            return (Criteria) this;
        }

        public Criteria andStudentSatusNotIn(List<Integer> values) {
            addCriterion("student_satus not in", values, "studentSatus");
            return (Criteria) this;
        }

        public Criteria andStudentSatusBetween(Integer value1, Integer value2) {
            addCriterion("student_satus between", value1, value2, "studentSatus");
            return (Criteria) this;
        }

        public Criteria andStudentSatusNotBetween(Integer value1, Integer value2) {
            addCriterion("student_satus not between", value1, value2, "studentSatus");
            return (Criteria) this;
        }

        public Criteria andStudentShaungyueIsNull() {
            addCriterion("student_shaungyue is null");
            return (Criteria) this;
        }

        public Criteria andStudentShaungyueIsNotNull() {
            addCriterion("student_shaungyue is not null");
            return (Criteria) this;
        }

        public Criteria andStudentShaungyueEqualTo(Integer value) {
            addCriterion("student_shaungyue =", value, "studentShaungyue");
            return (Criteria) this;
        }

        public Criteria andStudentShaungyueNotEqualTo(Integer value) {
            addCriterion("student_shaungyue <>", value, "studentShaungyue");
            return (Criteria) this;
        }

        public Criteria andStudentShaungyueGreaterThan(Integer value) {
            addCriterion("student_shaungyue >", value, "studentShaungyue");
            return (Criteria) this;
        }

        public Criteria andStudentShaungyueGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_shaungyue >=", value, "studentShaungyue");
            return (Criteria) this;
        }

        public Criteria andStudentShaungyueLessThan(Integer value) {
            addCriterion("student_shaungyue <", value, "studentShaungyue");
            return (Criteria) this;
        }

        public Criteria andStudentShaungyueLessThanOrEqualTo(Integer value) {
            addCriterion("student_shaungyue <=", value, "studentShaungyue");
            return (Criteria) this;
        }

        public Criteria andStudentShaungyueIn(List<Integer> values) {
            addCriterion("student_shaungyue in", values, "studentShaungyue");
            return (Criteria) this;
        }

        public Criteria andStudentShaungyueNotIn(List<Integer> values) {
            addCriterion("student_shaungyue not in", values, "studentShaungyue");
            return (Criteria) this;
        }

        public Criteria andStudentShaungyueBetween(Integer value1, Integer value2) {
            addCriterion("student_shaungyue between", value1, value2, "studentShaungyue");
            return (Criteria) this;
        }

        public Criteria andStudentShaungyueNotBetween(Integer value1, Integer value2) {
            addCriterion("student_shaungyue not between", value1, value2, "studentShaungyue");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordIsNull() {
            addCriterion("student_password is null");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordIsNotNull() {
            addCriterion("student_password is not null");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordEqualTo(String value) {
            addCriterion("student_password =", value, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordNotEqualTo(String value) {
            addCriterion("student_password <>", value, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordGreaterThan(String value) {
            addCriterion("student_password >", value, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("student_password >=", value, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordLessThan(String value) {
            addCriterion("student_password <", value, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordLessThanOrEqualTo(String value) {
            addCriterion("student_password <=", value, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordLike(String value) {
            addCriterion("student_password like", value, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordNotLike(String value) {
            addCriterion("student_password not like", value, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordIn(List<String> values) {
            addCriterion("student_password in", values, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordNotIn(List<String> values) {
            addCriterion("student_password not in", values, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordBetween(String value1, String value2) {
            addCriterion("student_password between", value1, value2, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordNotBetween(String value1, String value2) {
            addCriterion("student_password not between", value1, value2, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentTimeCountIsNull() {
            addCriterion("student_time_count is null");
            return (Criteria) this;
        }

        public Criteria andStudentTimeCountIsNotNull() {
            addCriterion("student_time_count is not null");
            return (Criteria) this;
        }

        public Criteria andStudentTimeCountEqualTo(Integer value) {
            addCriterion("student_time_count =", value, "studentTimeCount");
            return (Criteria) this;
        }

        public Criteria andStudentTimeCountNotEqualTo(Integer value) {
            addCriterion("student_time_count <>", value, "studentTimeCount");
            return (Criteria) this;
        }

        public Criteria andStudentTimeCountGreaterThan(Integer value) {
            addCriterion("student_time_count >", value, "studentTimeCount");
            return (Criteria) this;
        }

        public Criteria andStudentTimeCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_time_count >=", value, "studentTimeCount");
            return (Criteria) this;
        }

        public Criteria andStudentTimeCountLessThan(Integer value) {
            addCriterion("student_time_count <", value, "studentTimeCount");
            return (Criteria) this;
        }

        public Criteria andStudentTimeCountLessThanOrEqualTo(Integer value) {
            addCriterion("student_time_count <=", value, "studentTimeCount");
            return (Criteria) this;
        }

        public Criteria andStudentTimeCountIn(List<Integer> values) {
            addCriterion("student_time_count in", values, "studentTimeCount");
            return (Criteria) this;
        }

        public Criteria andStudentTimeCountNotIn(List<Integer> values) {
            addCriterion("student_time_count not in", values, "studentTimeCount");
            return (Criteria) this;
        }

        public Criteria andStudentTimeCountBetween(Integer value1, Integer value2) {
            addCriterion("student_time_count between", value1, value2, "studentTimeCount");
            return (Criteria) this;
        }

        public Criteria andStudentTimeCountNotBetween(Integer value1, Integer value2) {
            addCriterion("student_time_count not between", value1, value2, "studentTimeCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 22 10:22:42 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}