package com.ll.pojo;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_name
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_idCard
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String studentIdcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_phone
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String studentPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_project
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String studentProject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_cartime
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String studentCartime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_time
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private Integer studentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_satus
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private Integer studentSatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_shaungyue
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private Integer studentShaungyue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_password
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String studentPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_time_count
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private Integer studentTimeCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_name
     *
     * @return the value of student.student_name
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_name
     *
     * @param studentName the value for student.student_name
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_idCard
     *
     * @return the value of student.student_idCard
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getStudentIdcard() {
        return studentIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_idCard
     *
     * @param studentIdcard the value for student.student_idCard
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setStudentIdcard(String studentIdcard) {
        this.studentIdcard = studentIdcard == null ? null : studentIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_phone
     *
     * @return the value of student.student_phone
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getStudentPhone() {
        return studentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_phone
     *
     * @param studentPhone the value for student.student_phone
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setStudentPhone(String studentPhone) {
        this.studentPhone = studentPhone == null ? null : studentPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_project
     *
     * @return the value of student.student_project
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getStudentProject() {
        return studentProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_project
     *
     * @param studentProject the value for student.student_project
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setStudentProject(String studentProject) {
        this.studentProject = studentProject == null ? null : studentProject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_cartime
     *
     * @return the value of student.student_cartime
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getStudentCartime() {
        return studentCartime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_cartime
     *
     * @param studentCartime the value for student.student_cartime
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setStudentCartime(String studentCartime) {
        this.studentCartime = studentCartime == null ? null : studentCartime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_time
     *
     * @return the value of student.student_time
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public Integer getStudentTime() {
        return studentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_time
     *
     * @param studentTime the value for student.student_time
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setStudentTime(Integer studentTime) {
        this.studentTime = studentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_satus
     *
     * @return the value of student.student_satus
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public Integer getStudentSatus() {
        return studentSatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_satus
     *
     * @param studentSatus the value for student.student_satus
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setStudentSatus(Integer studentSatus) {
        this.studentSatus = studentSatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_shaungyue
     *
     * @return the value of student.student_shaungyue
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public Integer getStudentShaungyue() {
        return studentShaungyue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_shaungyue
     *
     * @param studentShaungyue the value for student.student_shaungyue
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setStudentShaungyue(Integer studentShaungyue) {
        this.studentShaungyue = studentShaungyue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_password
     *
     * @return the value of student.student_password
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getStudentPassword() {
        return studentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_password
     *
     * @param studentPassword the value for student.student_password
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setStudentPassword(String studentPassword) {
        this.studentPassword = studentPassword == null ? null : studentPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_time_count
     *
     * @return the value of student.student_time_count
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public Integer getStudentTimeCount() {
        return studentTimeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_time_count
     *
     * @param studentTimeCount the value for student.student_time_count
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setStudentTimeCount(Integer studentTimeCount) {
        this.studentTimeCount = studentTimeCount;
    }
}