package com.ll.pojo;

public class Trainer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainer.id
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainer.trainer_name
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String trainerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainer.trainer_status
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private Integer trainerStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trainer.trainer_card
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    private String trainerCard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainer.id
     *
     * @return the value of trainer.id
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainer.id
     *
     * @param id the value for trainer.id
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainer.trainer_name
     *
     * @return the value of trainer.trainer_name
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getTrainerName() {
        return trainerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainer.trainer_name
     *
     * @param trainerName the value for trainer.trainer_name
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setTrainerName(String trainerName) {
        this.trainerName = trainerName == null ? null : trainerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainer.trainer_status
     *
     * @return the value of trainer.trainer_status
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public Integer getTrainerStatus() {
        return trainerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainer.trainer_status
     *
     * @param trainerStatus the value for trainer.trainer_status
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setTrainerStatus(Integer trainerStatus) {
        this.trainerStatus = trainerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trainer.trainer_card
     *
     * @return the value of trainer.trainer_card
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public String getTrainerCard() {
        return trainerCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trainer.trainer_card
     *
     * @param trainerCard the value for trainer.trainer_card
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    public void setTrainerCard(String trainerCard) {
        this.trainerCard = trainerCard == null ? null : trainerCard.trim();
    }
}