package com.ll.mapper;

import com.ll.pojo.Messagetitle;
import com.ll.pojo.MessagetitleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface MessagetitleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_title
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    long countByExample(MessagetitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_title
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int deleteByExample(MessagetitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_title
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_title
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int insert(Messagetitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_title
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int insertSelective(Messagetitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_title
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    List<Messagetitle> selectByExample(MessagetitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_title
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    Messagetitle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_title
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") Messagetitle record, @Param("example") MessagetitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_title
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int updateByExample(@Param("record") Messagetitle record, @Param("example") MessagetitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_title
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int updateByPrimaryKeySelective(Messagetitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_title
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int updateByPrimaryKey(Messagetitle record);

    int insertAndReturnPrimaryKey(Messagetitle record);
}