package com.ll.mapper;

import com.ll.pojo.Publishmessage;
import com.ll.pojo.PublishmessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface PublishmessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_message
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    long countByExample(PublishmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_message
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int deleteByExample(PublishmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_message
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_message
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int insert(Publishmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_message
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int insertSelective(Publishmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_message
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    List<Publishmessage> selectByExampleWithBLOBs(PublishmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_message
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    List<Publishmessage> selectByExample(PublishmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_message
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    Publishmessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_message
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") Publishmessage record, @Param("example") PublishmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_message
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Publishmessage record, @Param("example") PublishmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_message
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int updateByExample(@Param("record") Publishmessage record, @Param("example") PublishmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_message
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int updateByPrimaryKeySelective(Publishmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_message
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Publishmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_message
     *
     * @mbg.generated Fri Dec 22 10:22:42 CST 2017
     */
    int updateByPrimaryKey(Publishmessage record);
}